GET https://www.deviantart.com/api/v1/oauth2/user/profile HTTP/1.1
@clientId=22803
@clientSecret=6919496f03acfdd6c3e463c747fa8be5


###

GET https://www.deviantart.com/api/v1/oauth2/user/profile
Authorization: oauth2 client_credentials job
